name: Build and publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - name: Install dependencies
      run: |
        python -m pip install install .[test]
    - name: Run lint
      run: |
        npm install -g pyright
        make code-style code-lint
    - name: Run test
      run: make test
    - name: Build
      run: |
        python -m pip install build --user
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish a Python distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
